#!/usr/bin/env bash
scriptpath=${1}
if [ -z "${scriptpath}" ]
then
  echo 'Must specify path to script as first parameter.' >&2
else
  shift
  shelltype=${1:-sh}
  echo \#\!/usr/bin/env "${shelltype}"'
' >"${scriptpath}"
  case ${shelltype} in
    bash)
      cat << EOF >> "${scriptpath}"
#Deduce this script's directory
if [ -z \${BASH_SOURCE} ]; then
  script_dir=\$(readlink -f \$(dirname "\${0}"))
else
  script_dir="\$(cd -P "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
fi
EOF
      ;;
  esac

  chmod 755 "${scriptpath}"
fi

