#!/usr/bin/env bash

#Deduce this script's directory
if [ -z ${BASH_SOURCE} ]; then
  script_dir=$(readlink -f $(dirname "${0}"))
else
  script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

declare -a runme_array
runme_array=( I was declared in the runme array )
export runme_array
echo "runme_array declared as: ${runme_array[@]}"

"${script_dir}/sub_process_script"

