#!/usr/bin/env bash

global_assert_runs=1
global_assert_errors=0

function _assert_description() {
  # Internal function to generate test name.
  # Globals:
  #  global_assert_runs
  # Parameters:
  #  1 - Test name
  # Outputs:
  #  Test name string
  local name

  name="${1}"
  echo "(test #${global_assert_runs}) ${name}"
}

function assert_exited_with_success() {
  # Parameters:
  #  1 - Test description.
  #  2 - Result exit code.
  # Returns:
  #  Result exit code.
  local description
  local exit_code

  description="${1}"
  if [ -z "${description}" ]
  then
    echo 'assert_exited_with_success expects a description as first parameter.'
    exit_code=2
  else
    shift

    if [[ ! "${1}" =~ ^-?[0-9]+$ ]]
    then
      echo 'You seem to be asserting without passing an exit code.' >&2
      echo "What is: '${1}'" >&2
      exit_code=1
    else
      exit_code=${1}
      if [[ ${exit_code} -ne 0 ]]
      then
        echo "ERROR $(_assert_description "${description}") exited with '${exit_code}'" >&2
      else
        echo "SUCCESS $(_assert_description "${description}")"
      fi
    fi
  fi

  (( global_assert_errors += ${exit_code} ))
  (( global_assert_runs += 1))
  return ${exit_code}
}

function assert_contains_text() {
  # Parameters:
  #  1     - Test description.
  #  2     - Expected text.
  #  3-... - Text to inspect.
  # Returns:
  #  0  - Assertion passed.
  #  <0 - Error in assertion parameters.
  #  >0 - Assertion failed.

  local description
  local text
  local check_count

  exit_code=0

  description="${1}"
  if [ -z "${description}" ]
  then
    echo 'assert_contains_text expects a description as the first parameter' >&2
    exit_code=-1
  else
    shift
    text="${1}"

    if [ -z "${text}" ]
    then
      echo 'assert_contains_text expected some text as the second parameter.' >&2
      exit_code=-2
    elif [ -z "${2}" ]
    then
      echo 'assert_contains_text expected some text to check for.' >&2
      exit_code=-3
    else
      shift

      check_count=0
      for check in "${@}"
      do
        if [[ ! "${text}" = *"${check}"* ]]
        then
          (( exit_code += 1 ))
          echo "Failure [${check_count}]: '${check}' not found in '${text}'" >&2
        fi

        (( check_count += 1))
      done

      if [ ${exit_code} -ne 0 ]
      then
        echo "FAILED $(_assert_description "${description}") with ${exit_code} missing strings" >&2
      else
        echo "SUCCESS $(_assert_description "${description}")"
      fi

      (( global_assert_runs += 1))
      (( global_assert_errors += ${exit_code} ))
    fi
  fi

  return ${exit_code}
}

run_tests=1

function assert_result_fails_with_error_text() {
  # Parameters:
  #  1 - Result of test code.
  #  2 - Result exit code.
  #  3 - Expected error text.
  #  4 - Test name.
  #  5 - [optional] Force test to run if not 0, regardless of global run_tests value.
  # E.g. assert_result_fails_with_error_text "$(my_function 2>&1)" ${?} 'expected some arguments' 'my_function no args'
  # Set global run_tests variable to 0 to turn off tests.

  local result
  local exit_code
  local error_text
  local name
  local _run_tests
  local assert_exit_code

  assert_exit_code=0
  result=${1}
  if [ ${assert_exit_code} -eq 0 ] && [ -z "${1}" ]
  then
    echo 'Result text not supplied' >&2
    assert_exit_code=1
  fi

  shift
  exit_code=${1}
  if [ ${assert_exit_code} -eq 0 ] && [[ ! "${1}" =~ ^-?[0-9]+$ ]]
  then
    echo "Exit code not correct: '${1}'" >&2
    assert_exit_code=2
  fi

  shift
  error_text=${1}
  if [ ${assert_exit_code} -eq 0 ] && [ -z "${1}" ]
  then
    echo 'Error text not supplied' >&2
    assert_exit_code=3
  fi

  shift
  name=${1}
  if [ ${assert_exit_code} -eq 0 ] && [ -z "${1}" ]
  then
    echo 'Name not supplied' >&2
    assert_exit_code=4
  fi

  if [ ${assert_exit_code} -eq 0 ]
  then
    shift
    _run_tests=${1:-${run_tests}}

    if [ ${_run_tests} -eq 1 ]
    then
      if [ ${exit_code} -eq 0 ]
      then
        echo "Expected ${name} to fail, but it succeeded !"
      else
        if [[ "${result}" = *"${error_text}"* ]]
        then
          echo "$(_assert_description "${name}") failed as expected. exit_code = ${exit_code}"
        else
          echo "$(_assert_description "${name}") failed but does not contain '${error_text}'. exit_code = ${exit_code}"
        fi
      fi
    fi
  fi

  (( global_assert_runs += 1))
  return ${assert_exit_code}
}
