#!/usr/bin/env sh

pathremove () {
  local NEWPATH
  local DIR
  local PATHVARIABLE=${2:-PATH}
  local PATHVALUE=$(eval echo -n \$${PATHVARIABLE})
  local OLDIFS="${IFS}"
  local IFS=':'
  for DIR in ${PATHVALUE}
  do
    if [ ! -z "${DIR}" ] && [ "$DIR" != "$1" ]
    then
      if [ -z "${NEWPATH}" ]
      then
        NEWPATH="${DIR}"
      else
        NEWPATH="${NEWPATH}"':'"${DIR}"
      fi
    fi
  done
  export $PATHVARIABLE="${NEWPATH}"
  IFS="${OLDIFS}"
}

pathprepend () {
  pathremove $1 $2
  local PATHVARIABLE=${2:-PATH}
  local PATHVALUE
  local delim
  PATHVALUE=$(eval echo -n \$${PATHVARIABLE})

  delim=''
  if [ ! -z "${PATHVALUE}" ]
  then
    delim=':'
  fi

  export $PATHVARIABLE="${1}${delim}${PATHVALUE}"
}

pathappend () {
  pathremove $1 $2
  local PATHVARIABLE=${2:-PATH}
  local PATHVALUE
  local delim
  PATHVALUE=$(eval echo -n \$${PATHVARIABLE})

  delim=''
  if [ ! -z "${PATHVALUE}" ]
  then
    delim=':'
  fi

  export $PATHVARIABLE="${PATHVALUE}${delim}${1}"
}