#!/usr/bin/env bash

#Deduce this script's directory
if [ -z ${BASH_SOURCE} ]; then
  script_dir=$(readlink -f $(dirname "${0}"))
else
  script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

# For some reason passing through --dry-run is fine,
# but the act of actually executing exits the while loop after first file.
# so instead do this:
# startscript fish
# copy_src_to_phone >>fish
# ./fish
# rm fish

shown_new=0
shown_modified=0

while read -r
do
  line="${REPLY}"

  case "${line}" in
    \?\?*)
      if [ ${shown_new} -eq 0 ]
      then
        echo '# New'
        shown_new=1
      fi
      ;;
    \ M*)
      if [ ${shown_modified} -eq 0 ]
      then
        echo '# Modified'
        shown_modified=1
      fi
      ;;
  esac

  echo "${script_dir}/copy_to_phone" "${@}" "$(pwd)/${line:3}" '"${@}"'
done < <(git status --porcelain --untracked-files)

