#!/usr/bin/env bash

#Deduce this script's directory
if [ -z ${BASH_SOURCE} ]; then
  script_dir=$(readlink -f $(dirname "${0}"))
else
  script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

# For some reason passing through --dry-run is fine,
# but the act of actually executing exits the while loop after first file.
# so instead do this:
# startscript fish
# copy_src_to_phone >>fish
# ./fish
# rm fish

shown_new=0
shown_modified=0
shown_deleted=0

while read -r
do
  line="${REPLY}"
  prefix="${script_dir}/copy_to_phone"

  case "${line}" in
    \?\?*)
      if [ ${shown_new} -eq 0 ]
      then
        echo '# New'
        shown_new=1
      fi
      echo "${prefix}" "${@}" "$(pwd)/${line:3}" '"${@}"'
      ;;
    \ D*)
      if [ ${shown_deleted} -eq 0 ]
      then
        echo '# Deleted so do a bit of this'
        echo "${prefix}" "${@}" "$(pwd)/delete_me" '"${@}"'
        cat <<EOF >./delete_me
#!/usr/bin/env bash
# Delete unwanted files from git

EOF
        chmod 755 ./delete_me
        shown_deleted=1
      fi
      echo "git rm --force \"$(pwd)/${line:3}\" '"${@}"'" >>./delete_me
      ;;
    \ M*)
      if [ ${shown_modified} -eq 0 ]
      then
        echo '# Modified'
        shown_modified=1
      fi
      echo "${prefix}" "${@}" "$(pwd)/${line:3}" '"${@}"'
      ;;
  esac

done < <(git status --porcelain --untracked-files | sort)

