#!/usr/bin/env sh
mkdir -p ~/fish/copyme/code/work/anaplan/hackathon/2018/zen_hacked
cp -r ~/code/work/anaplan/hackathon/2018/zen_hacked/pfour-jiraplan-configuration ~/fish/copyme/code/work/anaplan/hackathon/2018/zen_hacked
