#!/usr/bin/env bash

#Deduce this script's directory
if [ -z ${BASH_SOURCE} ]; then
  test_format_loop_script_dir=$(readlink -f $(dirname "${0}"))
else
  test_format_loop_script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

source "${test_format_loop_script_dir}/../../bash_script_logging"

test_loop_format_tokens() {
  local delimiter
  local s

  delimiter=$'\u2588'
  s='hi %<message> %<date>\n'

  echo '---test_loop_format_tokens---' >&2
  echo 'just running the loop...' >&2
  log::_loop_format_tokens "${s}" ${delimiter}>&2
  echo '' >&2

  echo 'reading through the loop...' >&2
  while IFS=${delimiter} read -r prefix token
  do
    echo "prefix='${prefix}'"
    echo "token='${token}'"
  done < <(log::_loop_format_tokens "${s}" ${delimiter})
}

test_loop_format_tokens

