#!/usr/bin/env bash

#Deduce this script's directory
if [ -z ${BASH_SOURCE} ]; then
  script_dir=$(readlink -f $(dirname "${0}"))
  script_path="${0}"
else
  script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  script_path="${BASH_SOURCE[0]}"
fi

script_file="${script_path##*/}"
absolute_script_path="${script_dir}/${script_file}"

args="${*}"
#real_alias_path=$(which alias)
falias=alias

#echo "args: '${args[@]}'"

left="${args%=*}"
right="${args#*=}"

#echo "left: '${left}'. right: '${right}'"

if [ "${left}" = 'ls' ] && [[ ! "${right}" =~ 'ls' ]]
then
    read -p 'Did you really think I would let you get away with this ? '
    #read -p 'No but really ? '
    #read -p 'REALLY ? '
    sl
else
  #set -x
  unalias alias
  if [ -z "${left}" ]
  then
    ${falias}
  else
    ${falias} "${left}"="${right}"
    ${falias} alias=". ${absolute_script_path}"
    #set +x
  fi
fi

