#!/usr/bin/env bash

result=1
if [ -f ${HOME}/temp/ssh-agent.sh ]
then  
  source ${HOME}/temp/ssh-agent.sh >/dev/null
  if [ -n ${SSH_AGENT_PID} ]
  then
    case $(uname) in
      MINGW*|mingw*|MSYS*|msys*)
        if ps_output=$(ps ${SSH_AGENT_PID})
        then
          if [[ "${ps_output}" == *ssh* ]]
          then
            result=0
          fi
        fi
        ;;
      *)
        if ps_output=$(ps ${SSH_AGENT_PID})
        then
          if [[ "${ps_output}" == *ssh* ]]
          then
            result=0
          fi
        fi
        ;;
    esac
  fi 
fi

exit ${result}

