#!/usr/bin/env sh

result=1
if [ -f ~/temp/ssh-agent.sh ]
then  
  . ~/temp/ssh-agent.sh >/dev/null
  if [ -n ${SSH_AGENT_PID} ]
  then
    case $(uname) in
      MINGW*|mingw*|MSYS*|msys*)
        ps -p ${SSH_AGENT_PID} >/dev/null
        result=${?}
        ;;
      *)
        ps -p ${SSH_AGENT_PID} >/dev/null
        result=${?}
        ;;
    esac
  fi 
fi

exit ${result}

