#!/usr/bin/env bash
# Type EOF to close out message

regex='([[:alnum:]]+-[[:digit:]]+)'

branch=$(git rev-parse --abbrev-ref HEAD)

if [[ "${branch}" =~ ${regex} ]]
then
  if [ -t 0 ]
  then
    git commit -m "${BASH_REMATCH[1]} ""${@}"
  else
    git commit -m "${BASH_REMATCH[1]} ""$(</dev/stdin)" "${@}"
  fi
else
  cat <<-EOF >&2
I couldn't work out the story from the branch name '${branch}'
EOF
fi
