#!/usr/bin/env bash
target=${1-.}

if [ "${target}" = "." ]; then
  function flurgh() {
    local d
    d=$(dirname "${1}")
    #Do not need the ./ at the front.
    echo "${d:2}"
  }
else
  function flurgh() {
    dirname "${1}"
  }
fi

export -f flurgh

while read -r
do
  # Filter out directories with no remote
  if ( cd "${REPLY}"; git config --get remote.origin.fetch >/dev/null )
  then
    echo "${REPLY}"
  fi
done < <(find ${target} -type d -name '.git' -exec bash -c 'flurgh "${0}"' {} \; )

