#!/usr/bin/env bash
repos_file="${1}"

declare -a remaining_args

if [ -n "${repos_file}" ] && [ -f "${repos_file}" ] && [[ "${repos_file}" =~ .*repos$ ]]
then
  remaining_args=( "${@:2}" )
else
  repos_file='repos'
  remaining_args=( "${@}" )
fi

if [ -f "${repos_file}" ]
then
  . "${repos_file}"
else
  echo "No ${repos_file} file found in $(pwd)."
fi

if [ -z ${repo_directories} ]
then
  echo 'Variable ${repo_directories} undefined.
Create a repos file in '$(pwd)' with:
declare -a repo_directories
repo_directories=( YOUR REPO DIRECTORIES HERE )'
fi

if [ -z ${repo_base} ]
then
  echo 'Variable ${repo_base} undefined.
Set to organisation url e.g.
repo_base=git@github.com:YOUR_ORG_HERE'
fi

if [ -z ${repo_directories} ] || [ -z ${repo_base} ]
then
  return 1
else
  return 0
fi

