#!/usr/bin/env bash

#Deduce this script's directory
if [ -z ${BASH_SOURCE} ]
then
  script_dir=$(readlink -f $(dirname "${0}"))
else
  script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

while read gitdir
do
  d=$(dirname "${gitdir}")
  pushd ${d} >/dev/null
  echo "---${d}---"
  eval "${@}" 
  popd >/dev/null
  echo
done < <(find . -name '.git' -type d)
#while read d
#do
#  pushd ${d} >/dev/null
#  echo "---${d}---"
#  git status
#  popd >/dev/null
#  echo
#done < <(find . -type d -maxdepth 1 -mindepth 1)
