#!/usr/bin/env sh
exit_code=0

. read_repos "${@}"

if [ ${?} -eq 0 ]
then
  if [ "${#remaining_args[@]}" -eq 0 ]
  then
    echo 'No branch specified.' >&2
    exit_code=1
  else
    for repo in "${repo_directories[@]}"
    do
      pushd "${repo}" >/dev/null
      if git show-ref --quiet --verify -- "refs/remotes/origin/${remaining_args[0]}"
      then
        echo "${repo}"
        #echo "${repo} origin/${remaining_args[@]}"
      fi
      popd >/dev/null
    done
  fi
fi

exit ${exit_code}
