#!/usr/bin/env bash

. read_repos "${@}"

if [ $? -eq 0 ]
then
  for repo in "${repo_directories[@]}"
  do
    pushd "${repo}" >/dev/null
    echo "${repo}" >&2
    eval "${remaining_args[@]}"
    popd >/dev/null
  done
fi

