#!/usr/bin/env bash

. read_repos "${@}"

if [ $? -eq 0 ]
then
  for d in "${repo_directories[@]}"; do
    echo "${d}"
    pushd "${d}" >/dev/null
    git status --porcelain | grep '^UU' | cut -c 4- | xargs -I {} sh -c 'git reset {} ; git checkout {};'
    popd >/dev/null
  done
fi

