#!/usr/bin/env bash

#Deduce this script's directory
if [ -z ${BASH_SOURCE} ]; then
  script_dir=$(readlink -f $(dirname "${0}"))
else
  script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

# Parameters:
# 1- Search string
# 2- Search directory (defaults to .)
# 3- Search include pattern (defaults to all)
# --color|--no-color
# --case
# All other parameters passed to grep

# Examples:
# Search for 'containerBuildPub' in current directory including all files giving context of 5 lines.
# srcgrep containerBuildPub . '*' -C5

# --binary-file=without-match means ignore binary files
declare -a args
declare -a extra_args

UNSET_COLOR=2
args=( "${@}" )
extra_args=()
color=${UNSET_COLOR}
case_sensitive=0
pattern=0
use_vim=0

function usage() {
  local program
  program="${0##*/}"
  cat <<EOF
${program} [-P|--pattern] SEARCH_STRING SEARCH_DIRECTORY SEARCH_PATTERN [--no-color] [EXTRA_ARGS...]
  Search source code for the specified search string (required).
  Start search in specified SEARCH_DIRECTORY, matching files with specified SEARCH_PATTERN.
 
Parameters:
  SEARCH_STRING    String to search for.
  SEARCH_DIRECTORY Directory to start search in. Defaults to .
  SEARCH_PATTERN   Pattern to match files against. Default is all files (*).
  --no-color       If specified, don't colourize output. Useful if piping.
  --color=COLOR    Overrides the default color=always with the specified setting.
  --case           If specfied, grep with case sensitivity.
  --vim            Pipe the output into vim and search for the search string.
  -P|--pattern     Treat SEARCH_STRING as a pattern.
  EXTRA_ARGS       All additional args passed to grep.
EOF
}

for ((i=0; i<${#args[@]}; ++i))
do
  arg="${args[${i}]}"
  case "${arg}" in
    --nocolor|--no-color)
      color=0
      ;;
    --color=*)
      extra_args=( "${arg}" "${extra_args[@]}" )
      color=0
      ;;
    --case)
      case_sensitive=1
      ;;
    -P|--pattern)
      pattern=1
      ;;
    --vim|--Vim|--VIM)
      use_vim=1
      ;;
    -h|--help|/?)
      usage
      exit 1
      ;;
    *)
        if [ -z "${search_string+x}" ]
        then
          search_string="${arg}"
        elif [ -z "${search_directory+x}" ]
        then
          search_directory="${arg}"
        elif [ -z "${search_pattern+x}" ]
        then
          search_pattern="${arg}"
        else
          extra_args+=( "${arg}" )
        fi
      ;;
  esac
done

if [ ${color} -eq ${UNSET_COLOR} ]
then
  if [ ${use_vim} -ne 0 ]
  then
    color=0
  else
    color=1
  fi
fi

if [ ${color} -ne 0 ]
then
  extra_args=( '--color=always' "${extra_args[@]}" )
fi

if [ ${case_sensitive} -eq 0 ]
then
  extra_args+=( '--ignore-case' )
fi

declare -a pattern_args
pattern_args=()
if [ ${pattern} -ne 0 ]
then
  case "$(uname -a | tr [:upper:] [:lower:])" in
    *darwin*)
      echo "It's Darwin baby."
      pattern_args+=( '--extended-regexp' )
      ;;
    *)
      pattern_args+=( '-P' )
      ;;
  esac
fi

pattern_args+=( "${search_string:?Must specific search string}" )

function search_like_crazy() {
  # -H Always include file name
  srcfind "${search_directory}" -type f -print0 | xargs -0 -n1 -P8 grep \
  "${pattern_args[@]}" \
  --binary-file=without-match \
  --line-number \
  -H \
  --include "${search_pattern:-*}" \
  --exclude 'gradlew.bat' \
  --exclude 'gradle' \
  "${extra_args[@]}"
}

if [ ${use_vim} -eq 0 ]
then
  search_like_crazy
else
  vim_case_arg=''
  if [ ${case_sensitive} -ne 0 ]
  then
    vim_case_arg='\c'
  fi
  # \c Case insensitive
  search_like_crazy | vim -R - -c "silent! /${search_string}${vim_case_arg}"
fi
#  --exclude-dir '.git' \
#  --exclude-dir 'build' \
#  --exclude-dir 'output' \
#  --exclude-dir 'out' \
#  --exclude-dir 'bin' \
#  --exclude-dir 'intermediate' \
#  --exclude-dir 'node_modules' \
#  --exclude-dir '.env' \
#  --exclude-dir '.idea' \
#  --exclude-dir '.gradle' \
#  --exclude-dir '.metadata' \
#  --exclude-dir '.plugins' \
#  --exclude-dir 'build-intellij' \
#  --exclude-dir 'target' \
 
