#!/usr/bin/env bash

declare -a args
declare -a extra_args

args=( "${@}" )
extra_args=()
specify_color=1
case_sensitive=0
pattern=0

function usage() {
  local program
  program="${0##*/}"
  cat <<EOF
${program} [-P|--pattern] SEARCH_STRING SEARCH_DIRECTORY SEARCH_PATTERN [--no-color] [EXTRA_ARGS...]
  Search source code for the specified search string (required).
  Start search in specified SEARCH_DIRECTORY, matching files with specified SEARCH_PATTERN.
 
Parameters:
  SEARCH_STRING    String to search for.
  SEARCH_DIRECTORY Directory to start search in. Defaults to .
  SEARCH_PATTERN   Pattern to match files against. Default is all files (*).
  --no-color       If specified, don't colourize output. Useful if piping.
  --color=COLOR    Overrides the default color=always with the specified setting.
  --case           If specfied, grep with case sensitivity.
  EXTRA_ARGS       All additional args passed to grep.

Examples:
# Search for 'containerBuildPub' in current directory including all files giving context of 5 lines.
srcgrep containerBuildPub . '*' -C5

# Search for 'works' in rust subdirectory including rust files
srcgrep works rust '*.rs'
EOF
}

for ((i=0; i<${#args[@]}; ++i))
do
  arg="${args[${i}]}"
  case "${arg}" in
    --nocolor|--no-color)
      specify_color=0
      ;;
    --color=*)
      extra_args=( "${arg}" "${extra_args[@]}" )
      specify_color=0
      ;;
    --case)
      case_sensitive=1
      ;;
    -h|--help|/?)
      usage
      exit 1
      ;;
    -P|--pattern)
      pattern=1
      ;;
    *)
        if [ -z "${search_string+x}" ]
        then
          search_string="${arg}"
        elif [ -z "${search_directory+x}" ]
        then
          search_directory="${arg}"
        elif [ -z "${search_pattern+x}" ]
        then
          search_pattern="${arg}"
        else
          extra_args+=( "${arg}" )
        fi
      ;;
  esac
done

if [ ${specify_color} -ne 0 ]
then
  extra_args=( '--color=always' "${extra_args[@]}" )
fi

if [ ${case_sensitive} -eq 0 ]
then
  extra_args+=( '--ignore-case' )
fi

declare -a pattern_args
pattern_args=()
if [ ${pattern} -ne 0 ]
then
  case "$(uname -a | tr [:upper:] [:lower:])" in
    *darwin*)
      pattern_args+=( '--extended-regexp' )
      ;;
    *)
      pattern_args+=( '-P' )
      ;;
  esac
fi

pattern_args+=( "${search_string:?Must specify search string}" )

# --binary-file=without-match means ignore binary files
grep --recursive \
  "${pattern_args[@]}" \
  "${search_directory:-.}" \
  --binary-file=without-match \
  --line-number \
  --include "${search_pattern:-*}" \
  --exclude-dir '.git' \
  --exclude-dir 'build' \
  --exclude-dir 'output' \
  --exclude-dir 'out' \
  --exclude-dir 'bin' \
  --exclude-dir 'intermediate' \
  --exclude-dir 'node_modules' \
  --exclude-dir '.env' \
  --exclude-dir '.idea' \
  --exclude-dir '.gradle' \
  --exclude-dir '.metadata' \
  --exclude-dir '.plugins' \
  --exclude-dir 'build-intellij' \
  --exclude-dir 'target' \
  --exclude 'gradlew.bat' \
  --exclude 'gradle' \
  "${extra_args[@]}"
