#!/usr/bin/env bash

# Parameters:
# 1- Search string
# 2- Search directory (defaults to .)
# 3- Search include pattern (defaults to all)
# All other parameters passed to grep

# Examples:
# Search for 'containerBuildPub' in current directory including all files giving context of 5 lines.
# srcgrep containerBuildPub . '*' -C5

# --binary-file=without-match means ignore binary files
declare -a args
declare -a extra_args

args=( "${@}" )
extra_args=()
color=1

function usage() {
  local program
  program="${0##*/}"
  cat <<EOF
${program} SEARCH_STRING SEARCH_DIRECTORY SEARCH_PATTERN [--no-color] [EXTRA_ARGS...]
  Search source code for the specified search string (required).
  Start search in specified SEARCH_DIRECTORY, matching files with specified SEARCH_PATTERN.
 
Parameters:
  SEARCH_STRING    String to search for.
  SEARCH_DIRECTORY Directory to start search in. Defaults to .
  SEARCH_PATTERN   Pattern to match files against. Default is all files (*).
  --no-color       If specified, don't colourize output. Useful if piping.
  --color=COLOR    Overrides the default color=always with the specified setting.
  EXTRA_ARGS       All additional args passed to grep.
EOF
}

for ((i=0; i<${#args[@]}; ++i))
do
  arg="${args[${i}]}"
  case "${arg}" in
    --nocolor|--no-color)
      color=0
      ;;
    --color=*)
      extra_args=( "${arg}" "${extra_args[@]}" )
      color=0
      ;;
    -h|--help|/?)
      usage
      exit 1
      ;;
    *)
        if [ -z "${search_string+x}" ]
        then
          search_string="${arg}"
        elif [ -z "${search_directory+x}" ]
        then
          search_directory="${arg}"
        elif [ -z "${search_pattern+x}" ]
        then
          search_pattern="${arg}"
        else
          extra_args+=( "${arg}" )
        fi
      ;;
  esac
done
#args=( "${@:4}" )
#
#for arg in "${args[@]}"
#do
#  case "${arg}" in
#    --nocolor|--no-color)
#      color=0
#      ;;
#    *)
#      extra_args+=( "${arg}" )
#      ;;
#  esac
#done
#
#if [ -t 0 ]
if [ ${color} -ne 0 ]
then
  extra_args=( '--color=always' "${extra_args[@]}" )
fi

grep --recursive \
  --ignore-case \
  "${search_string:?Must specific search string}" \
  "${search_directory:-.}" \
  --binary-file=without-match \
  --line-number \
  --include "${search_pattern:-*}" \
  --exclude-dir '.git' \
  --exclude-dir 'build' \
  --exclude-dir 'output' \
  --exclude-dir 'out' \
  --exclude-dir 'bin' \
  --exclude-dir 'node_modules' \
  --exclude-dir '.env' \
  --exclude-dir '.idea' \
  --exclude-dir '.gradle' \
  --exclude-dir '.metadata' \
  --exclude-dir '.plugins' \
  --exclude-dir 'build-intellij' \
  --exclude-dir 'target' \
  --exclude 'gradlew.bat' \
  --exclude 'gradle' \
  "${extra_args[@]}"
