#!/usr/bin/env bash
scriptpath=''
shelltype=''
shebang_shelltype=''

declare -a args
args=( "${@}" )
do_vim=0
force=0

for ((i=0; i<${#args[@]}; ++i))
do
  arg="${args[${i}]}"
  case "${arg}" in
    -f|--force)
      force=1
      ;;
    --vim)
      do_vim=1
      ;;
    *)
      if [ -z "${scriptpath}" ]
      then
        scriptpath="${arg}"
      elif [ -z "${shelltype}" ]
      then
        shelltype="${arg}"
      else
        echo "Unexpected arguments '${arg}'" >&2
      fi
      ;;
  esac
done

if [ -z "${scriptpath}" ]
then
  echo 'Must specify path to script as first parameter.' >&2
else
  case "${shelltype}" in
    '')
      shelltype='sh'
      shebang_shelltype="${shelltype}"
      ;;
    rawbash|bashraw)
      shebang_shelltype='bash'
      ;;
    *)
      shebang_shelltype="${shelltype}"
      ;;
  esac

  if [ -f "${scriptpath}" ] && [ ${force} -eq 0 ]
  then
    echo "Script '${scriptpath}' already exists. Specify --force to overwrite." >&2
    exit 1
  fi

  echo \#\!/usr/bin/env "${shebang_shelltype}"'
' >"${scriptpath}"
  case ${shelltype} in
    bash)
      cat << EOSCRIPT >> "${scriptpath}"
#Deduce this script's directory
if [ -z \${BASH_SOURCE} ]; then
  script_dir=\$(readlink -f \$(dirname "\${0}"))
else
  script_dir="\$(cd -P "\$(dirname "\${BASH_SOURCE[0]}")" && pwd)"
fi


output_file=''
ok_exit_code=0
declare -a args
args=( "\${@}" )

function usage() {
  local program_name
  program_name="\${0##*/}"

  cat <<EOF >&2
\${program_name} [-o|--output OUTPUT_FILE] [-h~--help]

Usage for this script.
E.g.
# Description of what this command does
\${program_name} somefile.txt
EOF
}


for (( i=0; i<\${#args[@]}; ++i ))
do
  arg="\${args[\${i}]}"
  case "\${arg}" in
    -o|--output)
      (( ++i ))
      if [ \${i} -eq \${#args[@]} ]
      then
        echo "Expected argument for '\${arg}'" >&2
        (( ++ok_exit_code ))
      else
        output_file="\${args[\${i}]}"
      fi
      ;;
    -h|--help|/\\?)
      usage
      exit 1
      ;;
    *)
      echo "Unexpected argument '\${arg}' to \$(basename "\${0}")" >&2
      (( ++ok_exit_code ))
      ;;
  esac
done

if [ -z "\${output_file}" ]
then
  echo "No output file specified" >&2
  (( ++ok_exit_code ))
fi

if [ \${ok_exit_code} -ne 0 ]
then
  exit \${ok_exit_code}
fi

EOSCRIPT
      ;;
  esac

  chmod 755 "${scriptpath}"

  if [ ${do_vim} -ne 0 ]
  then
    vim "+normal G$" +startinsert "${scriptpath}"
  fi
fi

