#!/usr/bin/env bash

function usage() {
  cat <<-EOF
$(basename ${0}) [--search-for] SEARCH [--delim] [-h|--help] [GREP ARGS]
Search for files with nce in the name.

Parameters:
  --delim             - Search for nce with a non-alphanumeric prefix.
  --search-for SEARCH - Search for string.
  -h|--help           - This usage information.
  GREP ARGS           - Additional arguments passed through to grep.
EOF
}

declare -a extra_args
extra_args=()
ok_exit_code=0

search_for=''
grep_pattern=''
use_delim=0

for ((i=1; i<${#}+1; ++i))
do
  arg="${!i}"
  case "${arg}" in
    --search-for)
      (( i++ ))
      if (( i < ${#} + 1 ))
      then
        arg="${!i}"
        search_for"${arg}"
      else
        echo 'No string to search for supplied' >&2
         (( ok_exit_code++ ))
      fi
      ;;
    --delim)
      use_delim=1
      grep_pattern='[^[:alnum:]]nce'
      ;;
    -h|--help|/?)
      usage
      exit 1
      ;;
    *)
      if [ -z "${search_for}" ]
      then
        search_for="${arg}"
      else
        extra_args+=( ${arg} )
      fi
      ;;
  esac
done

if [ -z "${search_for}" ]
then
  echo 'No search for string specified' >&2
  (( ok_exit_code++ ))
fi

if [ ${use_delim} -ne 0 ]
then
  grep_pattern="[^[:alnum:]]${search_for}"
fi

if [ ${ok_exit_code} -eq 0 ]
then
  find . \
    -type f \
    -name '*nce*' \
    ! \( \
    -path '*/.git*' -o\
    -name '*.swp' -o\
    -path ${0} -o \
    -name repos -o \
    -name '*.repos' \
    \) | grep -i "${grep_pattern}" "${extra_args[@]}"
fi

exit ${ok_exit_code}
