#!/usr/bin/env sh
target_dir="${HOME}/code/thirdparty/shscripts/git-aware-prompt.git"

if [ ! -d "${target_dir}/.git" ]
then
  git clone git://github.com/jimeh/git-aware-prompt.git "${target_dir}"
else
  pushd "${target_dir}"
  git fetch --prune
  git rebase
  popd
fi

