#!/usr/bin/env sh
target_dir="${HOME}/code/thirdparty/shscripts/gradle-completion.git"

if [ ! -d "${target_dir}/.git" ]
then
  git clone git@github.com:gradle/gradle-completion.git "${target_dir}"
else
  pushd "${target_dir}"
  git fetch
  git rebase
  popd
fi

