#!/usr/bin/env sh
target_dir="${HOME}/code/thirdparty/shscripts/gradle-completion.git"

if [ ! -d "${target_dir}/.git" ]
then
  url='gradle/gradle-completion.git'
  if [ -d "${HOME}/.ssh" ] && find "${HOME}/.ssh" -name '*.pub' | grep --quiet '.'
  then
    url="git://github.com/${url}"
  else
    url="https://github/com/${url}"
  fi
  git clone "${url}" "${target_dir}"
else
  pushd "${target_dir}"
  git fetch --prune
  git rebase
  popd
fi

