#!/usr/bin/env sh
download_file=$(mktemp)

trap cleanup 0

function cleanup() {
  rm -f "${download_file}"
}

function download_and_install() {
  local url
  local gradle_filename
  url="${1}"
  shift

  set -x
  #gradle_filename=$(echo "${latest_gradle_url}" | grep -o 'gradle-[0-9.-]\+all.zip')
  curl -L "${url}" -o "${download_file}"
  if [ ${?} -eq 0 ]
  then
    sudo unzip "${download_file}" -d "/opt/gradle"
    cleanup
  fi
  set +x
}

sudo mkdir -p /opt/gradle
release_page=$(curl -S https://gradle.org/releases/)
if [ -n "${release_page}" ]
then
  dq='"'
  sq="'"
  latest_gradle_url=$(echo "${release_page}" | grep -oh "href=[${sq}${dq}][a-zA-Z://.-]\+gradle-[0-9.]\+-all.zip" | cut -c 7- | sort -r | head -n 1)
  latest_gradle4_url=$(echo "${release_page}" | grep -oh "href=[${sq}${dq}][a-zA-Z://.-]\+gradle-4.[0-9.]\+-all.zip" | cut -c 7- | sort -t'.' -k4n | tail -n 1)
  echo "latest_gradle_url: '${latest_gradle_url}'"
  echo "latest_gradle4_url: '${latest_gradle4_url}'"

  download_and_install "${latest_gradle_url}"
  download_and_install "${latest_gradle4_url}"

fi
