#!/usr/bin/env bash

#Deduce this script's directory
if [ -z ${BASH_SOURCE} ]; then
  script_dir=$(readlink -f $(dirname "${0}"))
else
  script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

if [ ! -f "${script_dir}/brewlist.txt" ]
then
  echo 'No brewlist included to install from. Not installing brew components...'
else
  cat "${script_dir}/brewlist.txt" | xargs brew install
fi
