#!/usr/bin/env bash

#Deduce this script's directory
if [ -z ${BASH_SOURCE} ]; then
  script_dir=$(readlink -f $(dirname "${0}"))
else
  script_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
fi

rustup self update
rustup update stable
echo 'Vim Update...'
vim +PlugUpdate +PluginUpdate +CocUpdateSync +qall

"${script_dir}/install_fzf"
"${script_dir}/install_cmake"

